language: python
cache: pip
dist: xenial

if: commit_message !~ /appveyor/
jobs:
  include:
  - stage: Black Style Checking
    python: '3.7'
    install:
      - pip install -r requirements.txt
      - pip install -r dev.requirements.txt
      - pip install black
    script:
      - black --check --diff -l 79 --verbose pynvi/
      - black --check --diff -l 79 --verbose tests/
      - black --check --diff -l 79 --verbose setup.py
  - stage: Testing with Python 3.5
    python: '3.5'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    script: pytest tests/
  - stage: Testing with Python 3.6
    python: '3.6'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    script: pytest tests/
  - stage: Testing with Python 3.6
    python: '3.7'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    script: pytest tests/
  - stage: Covering Package
    python: '3.7'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    script:
    - pytest --cov pynvi tests/
    after_success: codecov --verbose
    deploy:
      provider: pypi
      user: erayerdin
      password:
        secure: "fUj+LqmNtep3lodKY4uOJcKAWZdirtI9l4vVQSJbPl3q05FEITdaQXjh9ACoVU2kyaB65PfGuty3AePgcUmM/5P4hgria3pRwXVaLNQN+H97k+qMCC/785YLLhZUhciYES2oKLcQb5RgpEZAvf526jsr7JfhsVdnvvrYgVlbUp7JJoUXwZ1Jnx0eOfJ7JNrq1jptdiwI+0KMf4rii2Y5SJWYVVOC//XOgAv3FAEDDMOjz963nDmc3xMyFYiK58XbNTNpHSwDd3xM8uFYaGD27dP5JqXbn5Pc0zyzBKo3m/g85czFSKSf0oq7jl21ma2OyyxI68H9VkrHw7A4Ny4NfI+0EVi8WUE71XAmFu5GSV/Q671WVgY7YmOKihkV2rV/RMrOkLy3wp87y0AgyRqDQ2GcOxwXhIvzTCnUoKP477BrVUMuQEDilWQlCr6WOCSsYZTFHUZR29aUvlWzhzborGJ4YrQUuw+iQ5udGpdC19sUbBhTAHyhtExKUqQHd2x1gTWJImr4DzuB2vNLHRqHVlpFoQ5EWF8DSBC1F33tvvXZH+m0LmO9utfoE5p09XbYDr5xqZnWZuyV1dS+8hI+guXothB5UDVHZ3FkRdJ39zhpNvD/PCBhn3EZCKrMtFY4+oFhArS4uJZXicNW9ct5n6sq+d/L7ZyMaMC4NcpkzGo="
      on:
        tags: true
